
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 588)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.output_lbl = QtWidgets.QLabel(self.centralwidget)
        self.output_lbl.setGeometry(QtCore.QRect(10, 10, 341, 91))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.output_lbl.setFont(font)
        self.output_lbl.setFrameShape(QtWidgets.QFrame.Box)
        self.output_lbl.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.output_lbl.setLineWidth(2)
        self.output_lbl.setText("")
        self.output_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.output_lbl.setObjectName("output_lbl")
        
        self.btn_percent = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.percent("%"))
        self.btn_percent.setGeometry(QtCore.QRect(10, 110, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn_percent.setFont(font)
        self.btn_percent.setObjectName("btn_percent")
        self.btn_arrow = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.remove_it())
        self.btn_arrow.setGeometry(QtCore.QRect(185, 110, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn_arrow.setFont(font)
        self.btn_arrow.setObjectName("btn_arrow")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("C"))
        self.btn_clear.setGeometry(QtCore.QRect(95, 110, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName("btn_clear")
        self.btn_div = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("/"))
        self.btn_div.setGeometry(QtCore.QRect(275, 110, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn_div.setFont(font)
        self.btn_div.setObjectName("btn_div")
        self.btn_mul = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("*"))
        self.btn_mul.setGeometry(QtCore.QRect(275, 200, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn_mul.setFont(font)
        self.btn_mul.setObjectName("btn_mul")
        self.btn_seven = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("7"))
        self.btn_seven.setGeometry(QtCore.QRect(10, 200, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn_seven.setFont(font)
        self.btn_seven.setObjectName("btn_seven")
        self.btn_eight = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("8"))
        self.btn_eight.setGeometry(QtCore.QRect(95, 200, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn_eight.setFont(font)
        self.btn_eight.setObjectName("btn_eight")
        self.btn_nine = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("9"))
        self.btn_nine.setGeometry(QtCore.QRect(185, 200, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn_nine.setFont(font)
        self.btn_nine.setObjectName("btn_nine")
        self.btn_sub = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("-"))
        self.btn_sub.setGeometry(QtCore.QRect(275, 290, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn_sub.setFont(font)
        self.btn_sub.setObjectName("btn_sub")
        self.btn_four = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("4"))
        self.btn_four.setGeometry(QtCore.QRect(10, 290, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn_four.setFont(font)
        self.btn_four.setObjectName("btn_four")
        self.btn_five = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("5"))
        self.btn_five.setGeometry(QtCore.QRect(95, 290, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn_five.setFont(font)
        self.btn_five.setObjectName("btn_five")
        self.btn_six = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("6"))
        self.btn_six.setGeometry(QtCore.QRect(185, 290, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn_six.setFont(font)
        self.btn_six.setObjectName("btn_six")
        self.btn_plus = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("+"))
        self.btn_plus.setGeometry(QtCore.QRect(275, 380, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn_plus.setFont(font)
        self.btn_plus.setObjectName("btn_plus")
        self.btn_one = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("1"))
        self.btn_one.setGeometry(QtCore.QRect(10, 380, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn_one.setFont(font)
        self.btn_one.setObjectName("btn_one")
        self.btn_two = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("2"))
        self.btn_two.setGeometry(QtCore.QRect(95, 380, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn_two.setFont(font)
        self.btn_two.setObjectName("btn_two")
        self.btn_three = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("3"))
        self.btn_three.setGeometry(QtCore.QRect(185, 380, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn_three.setFont(font)
        self.btn_three.setObjectName("btn_three")
        self.btn_equal = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.math())
        self.btn_equal.setGeometry(QtCore.QRect(275, 470, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn_equal.setFont(font)
        self.btn_equal.setObjectName("btn_equal")
        self.btn_add_div_sub = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("+/-"))
        self.btn_add_div_sub.setGeometry(QtCore.QRect(10, 470, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn_add_div_sub.setFont(font)
        self.btn_add_div_sub.setObjectName("btn_add_div_sub")
        self.btn_zero = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("0"))
        self.btn_zero.setGeometry(QtCore.QRect(95, 470, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn_zero.setFont(font)
        self.btn_zero.setObjectName("btn_zero")
        self.btn_decimal = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.decimal())
        self.btn_decimal.setGeometry(QtCore.QRect(185, 470, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btn_decimal.setFont(font)
        self.btn_decimal.setObjectName("btn_decimal")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def percent(self,op):
        try:
            value=float(self.output_lbl.text())
            
            percentage=value/100
            self.output_lbl.setText(f"{percentage}")
           
        except ValueError:
            self.output_lbl.setText("Error")

        

    #function for calculation
    def math(self):
        screen=self.output_lbl.text()
        result=eval(screen)
        self.output_lbl.setText(str(result))
    def remove_it(self):
        screen=self.output_lbl.text()
        screen=screen[:-1]
        self.output_lbl.setText(screen)

    #function for decimal
    def decimal(self):
        #store the current text
        current_text=self.output_lbl.text()
        #find the last part of the last opernad of the current text
        last_op=current_text.split("+")[-1].split("*")[-1].split("-")[-1].split("/")[-1]

        if "." not in last_op:
            self.output_lbl.setText(f"{current_text}.")
    def press_it(self,pressed):
        if pressed=="C":
            self.output_lbl.setText("0")
        else:
            #check to see if start with 0
            if self.output_lbl.text()=="0":
                self.output_lbl.setText("")
            #cancatenate pressed button with the output    
            self.output_lbl.setText(f"{self.output_lbl.text()}{pressed}")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.btn_percent.setText(_translate("MainWindow", "%"))
        self.btn_arrow.setText(_translate("MainWindow", "<<"))
        self.btn_clear.setText(_translate("MainWindow", "C"))
        self.btn_div.setText(_translate("MainWindow", "/"))
        self.btn_mul.setText(_translate("MainWindow", "*"))
        self.btn_seven.setText(_translate("MainWindow", "7"))
        self.btn_eight.setText(_translate("MainWindow", "8"))
        self.btn_nine.setText(_translate("MainWindow", "9"))
        self.btn_sub.setText(_translate("MainWindow", "-"))
        self.btn_four.setText(_translate("MainWindow", "4"))
        self.btn_five.setText(_translate("MainWindow", "5"))
        self.btn_six.setText(_translate("MainWindow", "6"))
        self.btn_plus.setText(_translate("MainWindow", "+"))
        self.btn_one.setText(_translate("MainWindow", "1"))
        self.btn_two.setText(_translate("MainWindow", "2"))
        self.btn_three.setText(_translate("MainWindow", "3"))
        self.btn_equal.setText(_translate("MainWindow", "="))
        self.btn_add_div_sub.setText(_translate("MainWindow", "+/-"))
        self.btn_zero.setText(_translate("MainWindow", "0"))
        self.btn_decimal.setText(_translate("MainWindow", "."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
