# Generated by Django 5.0.2 on 2024-06-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipe_Name', models.CharField(max_length=100)),
                ('Recipe_Descrption', models.TextField()),
                ('Recipe_Image', models.ImageField(upload_to='Recipe_img')),
            ],
        ),
    ]
