# Generated by Django 5.0.2 on 2024-06-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Recipe_tb',
        ),
    ]
