# Generated by Django 5.0.2 on 2024-06-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0002_rename_recipe_recipe_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe_tb',
            old_name='Recipe_Descrption',
            new_name='Recipe_Description',
        ),
    ]
