# Generated by Django 5.0.2 on 2024-06-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emplyee_delete_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
