# Generated by Django 5.0.2 on 2024-02-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0002_product_image_product_price_product_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='category',
        ),
    ]
